<?php



test('callback returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('strava.callback'));

    $response->assertRedirect(route('profile.edit'));

    // TODO: perform additional assertions
});

test('redirect returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('strava.redirect'));

    $response->assertRedirect('https://www.strava.com/oauth/authorize?' . $query);

    // TODO: perform additional assertions
});

// test cases...
