<?php



test('invoke returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('verification.verify', ['id' => $id, 'hash' => $hash]));

    $response->assertRedirect(route('home'));

    // TODO: perform additional assertions
});

// test cases...
