@php
$content = null;

if (isset($renderCallback) && is_callable($renderCallback)) {
    $content = $renderCallback($getState);
}

$platformClass = match($platform) {
    'linkedin' => 'bg-blue-50 border-blue-300',
    'twitter' => 'bg-blue-50 border-blue-300',
    default => 'bg-gray-50 border-gray-300'
};

$platformIcon = match($platform) {
    'linkedin' => '<svg class="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>',
    'twitter' => '<svg class="w-5 h-5 text-blue-500" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723 10.016 10.016 0 01-3.127 1.195 4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.937 4.937 0 004.604 3.417 9.868 9.868 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.054 0 13.999-7.496 13.999-13.986 0-.209 0-.42-.015-.63a9.936 9.936 0 002.46-2.548l-.047-.02z"/></svg>'
};

$platformName = match($platform) {
    'linkedin' => 'LinkedIn',
    'twitter' => 'Twitter/X',
    default => ucfirst($platform)
};
@endphp

<div class="p-4 border rounded-lg {{ $platformClass }}">
    <div class="flex items-center mb-3">
        <div class="mr-2">
            {!! $platformIcon !!}
        </div>
        <div class="font-medium">{{ $platformName }} Preview</div>
    </div>
    
    @if ($content)
        <div class="p-4 bg-white border rounded-lg">
            {{ $content }}
        </div>
        
        <div class="mt-3 text-xs text-gray-500">
            Generated by AI. Results may vary with each refresh.
        </div>
    @else
        <div class="p-4 bg-white border rounded-lg text-gray-500">
            Select a post to generate a preview.
        </div>
    @endif
</div>
