name: pint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pint-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, mysql
      - name: Install Dependencies
        run: |
          composer install
          npm install
          npm run build
      - name: Run Pint Tests
        run: ./vendor/bin/pint --test
